### ISSUE TITLE
The path to the sockets directory should be configurable

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-cli#5]
The socket files are currently stored in the home directory of the current user.
Unfortunately IIS default user has no access to its home directory so the jsreport exe doesn't work there.

There needs to be at least a configurable way to store the sockets somewhere else, perhaps in temp directory.

**Comment by pofider** [comment]
We decided to change the default location for cli helper files into
`[jsreport.tempDirectory]/cli/...`

@bjrmatos Please make it happen and add configuration option for cli to use a different path.

**Comment by bjrmatos** [comment]
looking at the implementation, since CLI code is running before getting access to jsreport instance, we don't have a way to get the `tempDirectory` at the right time when we need it. so we decided to join the temp directory (matching the new default temp directory of jsreport) right in the CLI and use it. we are going to use env var to allow specifying custom sockets directory.

example of inline usage:

```
cli_socketsDirectory=/path/to/socket-dir/ jsreport render ….
```
